version: 0.2te
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket lambdas-smartphotosearch --output-template-file outputsamtemplate.yml
artifacts:
  # type: zip
  files:
    - Server/Lambda/samTemplate.yaml
    - Server/Lambda/outputsamtemplate.yml
