version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file Server/Lambda/samTemplate.yaml --s3-bucket lambdas-smartphotosearch --output-template-file outputsamtemplate.json --use-json

  pre_build:
    commands:
      - echo Installing npm
      - npm --prefix ./Client/ install 
  build:
    commands:
      - echo building
      - npm --prefix ./Client/ run build 
      - ls -a
  
  post_build:
    commands:
      - ls -a
      - aws s3 cp --recursive --acl public-read ./Client/build s3://photo-album-hosting/
  

artifacts:
  # type: zip
  files:
    - samTemplate.yaml
    - outputsamtemplate.json
    - '**/*'
  base-directory: Client/build

