version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file Server/Lambda/samTemplate.yaml --s3-bucket lambdas-smartphotosearch --output-template-file outputsamtemplate.yml
artifacts:
  # type: zip
  files:
    - Server/Lambda/samTemplate.yaml
    - outputsamtemplate.yml
